server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: products
          uri: http://localhost:8082/
          predicates:
            - Path=/**
        - id: notification
          uri: http://localhost:8083/
          predicates:
            - Path=/**
        - id: authorization
          uri: http://localhost:8081/
          predicates:
            - Path=/**

logging:
  level:
    web: debug